### ISSUE TITLE
GPIO errors on default project

### ISSUE THREAD

**Issue by salmansheikh** [krtkl/snickerdoodle-examples#5]
Anyone know why in Vivado2019 I get these errors? I had to attach GPIO2 from the first axi_gpio_0 to GPIO1 output and similarly from the second to GPIO3 before running synthesis and implementation. Do I need to someone specify no connects to the gpio_tri_io signals?

![gpio_errors](https://user-images.githubusercontent.com/3300400/73137132-1e9f2280-4023-11ea-960f-efe7326db4f7.png)

**Comment by derekmulcahy** [comment]
I agree that the links become detached in the upgrade process.

Also the bitstream cannot be generated because of the errors shown in your screen dump. These errors are due to the constraints having become case sensitive somewhere along the Vivado upgrade path. If you edit the snickerdoodle_constraints.xdc file and change all the gpio[0123]_tri_io to GPIO[0123]_tri_io then you will have more success. I guess an alternative would be to change the GPIO* labels in the block design to gpio* but I haven't tried that.
